### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by GreepTheSheep** [codecat/op-style-manager#2]
A possibility to have with this plugin is to implement custom fonts

**Comment by Knackii** [comment]
And why not to have custom font size too :p

**Comment by codecat** [comment]
I just noticed this issue is in the style manager repository, which is not really correct. The style manager merely manages styles, it doesn't actually load them - Openplanet itself loads them. You should file this issue here, instead: https://github.com/openplanet-nl/issues/issues
